name: Formal Verification

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - '**'
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/verification.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/verification.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  kani-proofs:
    name: Kani Model Checker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Kani
        uses: model-checking/kani-github-action@v1
        with:
          args: '--jobs 4 --output-format=terse --unstable stubbing'
